import type { CopyCatalog } from "./types";

export const defaultCopy: CopyCatalog = {
  loading: "正在准备你的工作空间…",
  brandTagline: "你的本地工作搭档",
  footerTrust: "你选择，搭手才使用",
  mainNavigation: "主导航",
  setupTitle: "让这台电脑用上搭手",
  setupIntro: "点一下，我们会为这台电脑准备好搭手。完成后，你只需选择愿意让 ChatGPT 使用的工作文件夹。",
  startSetup: "开始使用搭手",
  submitting: "正在准备…",
  trialIdle: "还没有开始",
  trialPendingTitle: "已经收到，正在准备",
  trialPendingBody: "我们正在为这台电脑准备连接。通常几分钟内会有结果，你可以先关闭窗口。",
  trialProvisioningTitle: "正在为这台电脑准备搭手",
  trialProvisioningBody: "连接正在最后检查，很快就可以选择工作文件夹了。",
  trialSlow: "这次准备得比平时久一些。你可以重新检查；关闭窗口不会中断准备。",
  progressReceived: "已经收到",
  progressPreparing: "正在准备",
  progressChecking: "正在检查",
  progressReady: "准备完成",
  readyTitle: "搭手已经准备好了",
  readyBody: "现在请选择一个或多个工作文件夹。文件读取和修改只会在你选择的文件夹中进行。",
  chooseFolders: "选择工作文件夹",
  chooseFoldersHint: "可以一次选择多个文件夹，也可以之后随时调整。",
  folderPickerTitle: "选择工作文件夹",
  folderListLabel: "已选择的工作文件夹",
  keepOneFolder: "至少保留一个工作文件夹",
  addFolder: "添加文件夹",
  removeFolder: "移除",
  noFolders: "还没有选择文件夹",
  startUsing: "开始使用",
  trustTitle: "你始终做主",
  trustBody: "读取和修改文件只会在你选择的文件夹里进行。项目命令默认关闭；你主动开启后，命令会使用这台电脑上你的账户权限，但不会获得搭手或云端凭据。",
  failureTitle: "这次没有准备好",
  failureBody: "可能是网络暂时不稳定，也可能是连接还在准备中。你可以重新试一次；如果仍然不行，把排查信息发给我们。",
  retry: "重新准备",
  copyDiagnostics: "复制排查信息",
  preparing: "正在准备",
  connecting: "正在连接",
  ready: "电脑端已经准备好了",
  recovering: "正在恢复连接",
  blocked: "需要重新启动",
  stopped: "尚未启动",
  openChatGPT: "打开 ChatGPT",
  copyPassword: "复制授权密码",
  passwordCopied: "授权密码已复制",
  copyAddress: "复制连接地址",
  addressCopied: "连接地址已复制",
  residentNote: "关闭窗口后，搭手仍会在顶部菜单栏运行。需要停止服务时，请从菜单栏选择“退出搭手”。",
  settings: "设置",
  settingsIntro: "让搭手安静地陪着你工作，需要时再回来继续。",
  currentVersion: "当前版本",
  use: "使用",
  helpTitle: "连接 ChatGPT 时卡住了？",
  helpBody: "按当前页的 1/3 → 2/3 → 3/3 操作。名称、描述、连接地址和授权密码都可以直接复制。",
  helpPath: "如果看不到“创建应用”：打开 ChatGPT 设置 → 插件 → 开发者模式，勾选“开发人员模式”和“在开发者模式下强制执行 CSP”。",
  autostart: "登录电脑时自动启动搭手",
  autostartHint: "启动后会安静地留在顶部菜单栏，不会打扰你。",
  notifications: "准备好后提醒我",
  notificationsHint: "只在你主动打开后发送系统通知。",
  projectCommands: "允许 ChatGPT 运行项目命令",
  projectCommandsHint: "默认关闭。开启后可运行测试、构建和 Git 检查；命令使用你的电脑账户权限，不是系统沙箱。搭手和云端凭据不会交给命令。",
  checkUpdate: "检查更新",
  checkingUpdate: "正在检查…",
  updateReady: "更新已准备好，重启后生效",
  updateFound: "发现新版本，先看看这次更新了什么。",
  updateAvailable: "可更新到",
  updateNotesUnavailable: "这次主要包含稳定性和体验改进。",
  updateLater: "稍后再说",
  installUpdate: "更新并重新打开",
  installingUpdate: "正在更新…",
  updateInstallFailure: "这次没有更新成功，当前版本仍可继续使用。",
  alreadyLatest: "当前已经是最新版本",
  advanced: "高级与故障恢复",
  importInvite: "导入管理员邀请文件",
  configureAgain: "重新选择文件夹",
  workspaceEyebrow: "你的工作空间",
  connectedEyebrow: "ChatGPT 已连接",
  connectingEyebrow: "正在检查连接",
  recoveringEyebrow: "连接需要一点时间",
  readyHint: "本机已经正常运行。接下来按下面的步骤把搭手添加到 ChatGPT，通常约 1 分钟。",
  recoveringHint: "连接检查比平时慢一点，搭手会继续尝试。你仍然可以复制授权密码。",
  workingHint: "搭手正在处理连接，你可以稍等一下。",
  savingFolders: "正在保存…",
  foldersSaved: "工作文件夹已保存，可以开始了。",
  reconnecting: "正在重新连接，很快就好。",
  chatgptOpened: "ChatGPT 已打开。继续按当前步骤操作。",
  diagnosticsFailure: "排查信息没有复制成功，请再试一次。",
  statusReady: "搭手已经准备好了",
  applicationReceived: "已经收到，搭手正在准备这台电脑。",
  diagnosticsCopied: "排查信息已复制",
  troubleshootingTitle: "搭手排查卡",
  troubleshootingHint: "遇到问题时，截图当前页面，再把这张卡和排查信息一起发给我们。",
  currentStatus: "当前状态",
  currentStep: "当前步骤",
  deviceLabel: "设备",
  recentCheck: "最近检查",
  applicationLabel: "准备状态",
  applicationNotStarted: "还没有开始",
  applicationWaiting: "等待确认",
  applicationPreparing: "正在准备",
  applicationReady: "已经准备好",
  applicationRejected: "需要重新确认",
  applicationEnded: "已结束",
  stepNotApplied: "还没有开始",
  stepWaitingConfirmation: "等待确认",
  stepPreparingConnection: "正在联系服务",
  stepStartingLocalService: "正在启动搭手",
  stepRecoveringConnection: "正在恢复连接",
  stepReady: "可以开始工作",
  stepRuntimeBlocked: "需要重新启动",
  stepOtherConnection: "另一套连接正在使用",
  stepNeedsAttention: "需要查看原因",
  updateUnavailable: "暂时无法检查更新，请稍后再试。",
  autostartFailure: "系统没有接受自动启动设置，但搭手仍然可以正常使用。",
  notificationUnavailable: "没有开启系统通知；你仍然可以随时回来查看。",
  settingsSaveFailure: "设置没有保存成功，请再试一次。",
  inviteImported: "邀请文件已导入，请继续选择工作文件夹。",
  inviteImportFailure: "没有导入成功，请让管理员重新发一份。",
  passwordNotReady: "授权密码还没有准备好，请稍后再试。",
  chatgptFailure: "ChatGPT 没有打开，请稍后再试。",
  addressFailure: "连接地址没有复制成功，请再试一次。",
  folderPickerFailure: "没有打开文件夹选择器。",
  foldersSaveFailure: "工作文件夹没有保存成功，原来的设置仍然保留。",
  errorOtherProcess: "搭手发现另一套连接正在使用这台电脑，为了安全没有结束它。",
  errorControlTimeout: "网络暂时有点慢，请稍后再试。",
  errorControlConnect: "暂时联系不上搭手服务，请稍后再试。",
  errorControlResponse: "搭手服务暂时没有返回完整结果，请稍后再试。",
  errorRuntimeStart: "搭手这次没有启动成功。你可以重新准备；如果仍然不行，把排查信息发给我们。",
  errorRuntimeHealthTimeout: "搭手已经启动，但本机服务一直没有准备好。请点击“重新准备”；如果仍然不行，把排查信息发给我们。",
  errorNotConfigured: "搭手还没有准备好，请先完成第一次设置。",
  errorMissingResources: "安装内容不完整，请重新安装最新版本。",
  errorNoRoots: "请至少选择一个工作文件夹。",
  errorInvalidRoot: "请选择真实存在的工作文件夹。",
  errorDuplicateRoot: "同一个工作文件夹只需要添加一次。",
  errorInvite: "邀请文件没有导入成功，请让管理员重新发一份。",
  notificationTitle: "搭手已经准备好了",
  notificationBody: "回来选择工作文件夹，然后连接 ChatGPT。",
  uiFailureTitle: "页面这次没有打开好",
  uiFailureBody: "你的工作文件夹和连接仍然安全保留。重新打开搭手就可以继续。",
  reloadUi: "重新打开搭手",
  computerReadyEyebrow: "电脑端准备完成",
  computerReadyTitle: "电脑端已经准备好了",
  computerReadyBody: "还差一步：把搭手添加到 ChatGPT。连接地址会自动复制，通常约 1 分钟。",
  connectChatGPT: "连接 ChatGPT",
  connectStepOne: "打开开发者模式",
  connectStepTwo: "创建搭手",
  connectStepThree: "完成授权",
  developerModeTitle: "先确认 ChatGPT 已打开开发者模式",
  developerModeBody: "只需设置一次。进入下面的位置，并勾选两项开关。",
  developerModePath: "设置 → 插件 → 开发者模式",
  developerModeChecks: "勾选“开发人员模式”和“在开发者模式下强制执行 CSP”",
  openedDeveloperMode: "我已经打开",
  createAppTitle: "在 ChatGPT 创建搭手",
  createAppBody: "在 ChatGPT 的插件页面点击“创建应用”，然后按下面填写。每一项都可以直接复制，不用手动输入。",
  appNameLabel: "名称",
  appNameValue: "搭手",
  appDescriptionLabel: "描述",
  appDescriptionValue: "让我在授权的本地工作区中工作",
  serverUrlLabel: "服务器 URL",
  authenticationLabel: "身份验证",
  authenticationValue: "OAuth",
  copyValue: "复制",
  copiedName: "名称已复制",
  copiedDescription: "描述已复制",
  copiedAddressForSetup: "连接地址已复制，请粘贴到服务器 URL",
  reopenChatGPT: "重新打开 ChatGPT",
  waitingForAuthorization: "正在等 ChatGPT 确认连接，完成后这里会自动更新。",
  authorizationBody: "浏览器中的授权页已经打开。现在回到搭手复制授权密码，再粘贴到浏览器，不需要填写其他内容。",
  oauthCompletedTitle: "授权已经完成",
  oauthCompletedBody: "不用再复制密码。ChatGPT 正在完成最后的连接确认，请保留搭手运行。",
  chatgptConnectedTitle: "ChatGPT 已连接",
  chatgptConnectedBody: "先用一个只读任务确认搭手能看到你选择的项目，不会修改文件。",
  firstTaskPrompt: "请列出我选择的项目，并告诉我每个项目是做什么的。先不要修改文件。",
  copyTaskAndOpen: "复制任务并打开 ChatGPT",
  firstTaskCompletedTitle: "搭手已经可以干活了",
  firstTaskCompletedBody: "ChatGPT 已经成功使用过搭手。现在可以继续描述你的真实任务。",
  startConnectionOpened: "连接地址已复制，ChatGPT 已打开。按搭手里的步骤继续即可。",
  connectedHint: "电脑端和 ChatGPT 的连接都正常。再完成下面这个只读任务，就能确认工作区可用。",
  firstTaskHint: "电脑端、ChatGPT 和工作区都已经验证通过。现在可以开始真实任务。",
  chatgptStatusLabel: "ChatGPT 连接",
  chatgptNotStarted: "还未开始",
  chatgptSetupOpened: "正在创建搭手",
  chatgptAuthorizationRequested: "等待授权密码",
  chatgptOauthCompleted: "授权已完成",
  chatgptConnected: "已经连接",
  chatgptFirstTaskCompleted: "首次任务成功",
};

export function mergeCopy(value: unknown): CopyCatalog {
  if (!value || typeof value !== "object") return defaultCopy;
  const candidate = value as Record<string, unknown>;
  return Object.fromEntries(Object.keys(defaultCopy).map((key) => [
    key,
    typeof candidate[key] === "string" && candidate[key].trim() ? candidate[key] : defaultCopy[key as keyof CopyCatalog],
  ])) as CopyCatalog;
}
